import type { FlightOption, HotelOption } from "./types";

export const CATALOG_DISCLAIMER =
  "DEMO CATALOG — curated, deterministic sample inventory for this hackathon. Not live GDS, OTA, or booking data. No purchases are made.";

export const HOTELS: HotelOption[] = [
  {
    id: "station-house-akihabara",
    name: "Station House Akihabara",
    neighborhood: "Akihabara",
    nightlyUsd: 183,
    walkMinutesToStation: 4,
    station: "JR Akihabara",
    quietScore: 2,
    notes: "Business hotel stacked above the JR lines.",
    source: "demo_catalog",
  },
  {
    id: "capsule-ueno",
    name: "Ueno Capsule North",
    neighborhood: "Ueno",
    nightlyUsd: 89,
    walkMinutesToStation: 24,
    station: "JR Ueno",
    quietScore: 1,
    notes: "Cheapest bed in the catalog, far from the nearest station entrance.",
    source: "demo_catalog",
  },
  {
    id: "gracery-shinjuku",
    name: "Gracery Shinjuku East",
    neighborhood: "Shinjuku",
    nightlyUsd: 198,
    walkMinutesToStation: 3,
    station: "JR Shinjuku",
    quietScore: 2,
    notes: "Godzilla-adjacent, loud at night, extremely convenient.",
    source: "demo_catalog",
  },
  {
    id: "richmond-musashino",
    name: "Richmond Premier Musashino",
    neighborhood: "Kichijoji",
    nightlyUsd: 149,
    walkMinutesToStation: 6,
    station: "JR Kichijoji",
    quietScore: 4,
    notes: "Residential west-side stay, strong value under $150.",
    source: "demo_catalog",
  },
  {
    id: "toyoko-nihonbashi",
    name: "Toyoko Inn Nihonbashi",
    neighborhood: "Nihonbashi",
    nightlyUsd: 128,
    walkMinutesToStation: 5,
    station: "Tokyo Metro Mitsukoshimae",
    quietScore: 3,
    notes: "Reliable business chain, compact rooms.",
    source: "demo_catalog",
  },
  {
    id: "mitsui-kyobashi",
    name: "Mitsui Garden Kyobashi",
    neighborhood: "Kyobashi",
    nightlyUsd: 175,
    walkMinutesToStation: 2,
    station: "Tokyo Station Yaesu",
    quietScore: 3,
    notes: "Two minutes from Tokyo Station's Yaesu exit.",
    source: "demo_catalog",
  },
  {
    id: "apa-shibuya",
    name: "APA Hotel Shibuya",
    neighborhood: "Shibuya",
    nightlyUsd: 162,
    walkMinutesToStation: 8,
    station: "JR Shibuya",
    quietScore: 2,
    notes: "Central, lively, slightly longer walk.",
    source: "demo_catalog",
  },
  {
    id: "unizo-shinagawa",
    name: "Unizo Inn Shinagawa",
    neighborhood: "Shinagawa",
    nightlyUsd: 141,
    walkMinutesToStation: 4,
    station: "JR Shinagawa",
    quietScore: 3,
    notes: "Airport-line adjacent, easy late arrivals.",
    source: "demo_catalog",
  },
  {
    id: "sunroute-ginza",
    name: "Sunroute Ginza",
    neighborhood: "Ginza",
    nightlyUsd: 189,
    walkMinutesToStation: 7,
    station: "Ginza Station",
    quietScore: 3,
    notes: "Shopping-district stay with evening quiet after 10pm.",
    source: "demo_catalog",
  },
  {
    id: "super-ikebukuro",
    name: "Super Hotel Lohas Ikebukuro",
    neighborhood: "Ikebukuro",
    nightlyUsd: 118,
    walkMinutesToStation: 11,
    station: "JR Ikebukuro",
    quietScore: 3,
    notes: "Value stay just outside the 10-minute transit preference.",
    source: "demo_catalog",
  },
  {
    id: "via-akasaka",
    name: "Via Inn Prime Akasaka",
    neighborhood: "Akasaka",
    nightlyUsd: 154,
    walkMinutesToStation: 5,
    station: "Akasaka-mitsuke",
    quietScore: 4,
    notes: "Diplomatic-area quiet with subway access.",
    source: "demo_catalog",
  },
  {
    id: "daiwa-akihabara",
    name: "Daiwa Roynet Akihabara",
    neighborhood: "Akihabara",
    nightlyUsd: 167,
    walkMinutesToStation: 3,
    station: "JR Akihabara",
    quietScore: 3,
    notes: "Newer rooms, still above the electric town.",
    source: "demo_catalog",
  },
  {
    id: "sotetsu-kanda",
    name: "Sotetsu Fresa Inn Kanda",
    neighborhood: "Kanda",
    nightlyUsd: 136,
    walkMinutesToStation: 4,
    station: "JR Kanda",
    quietScore: 3,
    notes: "One stop from Tokyo Station, under $150.",
    source: "demo_catalog",
  },
  {
    id: "knot-shinjuku",
    name: "The Knot Tokyo Shinjuku",
    neighborhood: "Shinjuku",
    nightlyUsd: 210,
    walkMinutesToStation: 6,
    station: "JR Shinjuku",
    quietScore: 2,
    notes: "Over the $200 demo budget unless the human raises it.",
    source: "demo_catalog",
  },
];

export const FLIGHTS: FlightOption[] = [
  {
    id: "sq638",
    carrier: "Singapore Airlines",
    number: "SQ638",
    from: "SIN",
    to: "HND",
    departLocal: "23:55",
    arriveLocal: "07:35",
    window: "late",
    durationMinutes: 400,
    priceUsd: 412,
    stops: 0,
    source: "demo_catalog",
  },
  {
    id: "jl712",
    carrier: "Japan Airlines",
    number: "JL712",
    from: "SIN",
    to: "HND",
    departLocal: "01:05",
    arriveLocal: "08:50",
    window: "late",
    durationMinutes: 405,
    priceUsd: 398,
    stops: 0,
    source: "demo_catalog",
  },
  {
    id: "sq12",
    carrier: "Singapore Airlines",
    number: "SQ12",
    from: "SIN",
    to: "NRT",
    departLocal: "08:30",
    arriveLocal: "16:20",
    window: "early",
    durationMinutes: 410,
    priceUsd: 455,
    stops: 0,
    source: "demo_catalog",
  },
  {
    id: "nh802",
    carrier: "All Nippon Airways",
    number: "NH802",
    from: "SIN",
    to: "HND",
    departLocal: "14:20",
    arriveLocal: "22:10",
    window: "afternoon",
    durationMinutes: 410,
    priceUsd: 438,
    stops: 0,
    source: "demo_catalog",
  },
  {
    id: "tr808",
    carrier: "Scoot",
    number: "TR808",
    from: "SIN",
    to: "NRT",
    departLocal: "22:10",
    arriveLocal: "06:05",
    window: "late",
    durationMinutes: 415,
    priceUsd: 289,
    stops: 0,
    source: "demo_catalog",
  },
  {
    id: "sq636",
    carrier: "Singapore Airlines",
    number: "SQ636",
    from: "SIN",
    to: "HND",
    departLocal: "09:45",
    arriveLocal: "17:35",
    window: "early",
    durationMinutes: 400,
    priceUsd: 401,
    stops: 0,
    source: "demo_catalog",
  },
  {
    id: "cx714",
    carrier: "Cathay Pacific",
    number: "CX714",
    from: "SIN",
    to: "HND",
    departLocal: "11:00",
    arriveLocal: "21:40",
    window: "afternoon",
    durationMinutes: 520,
    priceUsd: 367,
    stops: 1,
    source: "demo_catalog",
  },
  {
    id: "sq622",
    carrier: "Singapore Airlines",
    number: "SQ622",
    from: "SIN",
    to: "HND",
    departLocal: "18:05",
    arriveLocal: "02:00",
    window: "afternoon",
    durationMinutes: 415,
    priceUsd: 429,
    stops: 0,
    source: "demo_catalog",
  },
];
